version: "3.3"

services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - 4566:4566
    container_name: localstack
    environment:
      - SERVICES=s3,sqs,dynamodb

  localstack-init:
    image: localstack-init
    build:
      context: images/localstack
    container_name: localstack-init
    depends_on:
      - localstack

  dks:
    image: dks
    ports:
      - 8443:8443
    build:
      context: images/dks
    container_name: dks
